/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.lounge.api;

import io.lounge.models.InlineResponse200;
import io.lounge.models.User;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-16T12:49:56.829Z")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "Log user in", nickname = "login", notes = "Log user in", response = InlineResponse200.class, tags={ "auth", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = InlineResponse200.class),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/login",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse200> login(@ApiParam(value = "The user who wants to log in", required = true) @Valid @RequestBody User user);

}
