/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.lounge.api;

import io.lounge.models.NewUser;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-16T12:49:56.829Z")

@Api(value = "register", description = "the register API")
public interface RegisterApi {

    @ApiOperation(value = "Register new user", nickname = "register", notes = "Register new user", response = Boolean.class, tags={ "auth", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Boolean.class),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/register",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Boolean> register(@ApiParam(value = "The new user to register", required = true) @Valid @RequestBody NewUser newUser);

}
