/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.lounge.api.interfaces;

import io.lounge.models.Notification;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-20T12:30:38.803Z")

@Api(value = "notifications", description = "the notifications API")
public interface NotificationsApi {

    @ApiOperation(value = "Get all notifications of user", nickname = "getNotifications", notes = "Return the user's notifications", response = Notification.class, responseContainer = "List", tags={ "notifications", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Notification.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/notifications/{username}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Notification>> getNotifications(@ApiParam(value = "",required=true) @PathVariable("username") String username);

}
