/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.lounge.api.interfaces;

import io.lounge.models.NewUser;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-16T12:49:56.829Z")

@Api(value = "settings", description = "the settings API")
public interface SettingsApi {

    @ApiOperation(value = "settings for user changes", nickname = "settings", notes = "Allow user to access settings", response = Boolean.class, tags={ "settings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Changes Succesful", response = Boolean.class),
        @ApiResponse(code = 400, message = "Invalid input"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/settings",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Boolean> settings(@ApiParam(value = "new values for user", required = true) @NotNull @Valid @RequestBody NewUser userChanges);

}
